apiVersion: v1
kind: Namespace
metadata:
  name: examples
  labels:
    name: examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  namespace: examples
spec:
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
      - name: getting-started
        image: docker/getting-started:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: getting-started
  namespace: examples
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: getting-started
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: getting-started
  namespace: examples
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # external-dns.alpha.kubernetes.io/hostname: "getting-started.apps.BASE_DOMAIN"
    # external-dns.alpha.kubernetes.io/ttl: "120"
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  tls:
  - hosts:
    - getting-started.apps.BASE_DOMAIN
    secretName: getting-started-tls
  rules:
  - host: getting-started.apps.BASE_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: getting-started
            port:
              number: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: examples
  labels:
    deploymentName: getting-started
spec:
  scaleTargetRef:
    kind: Deployment
    name: getting-started
  pollingInterval: 30
  minReplicaCount: 0
  maxReplicaCount: 1
  advanced:                                 
    restoreToOriginalReplicaCount: false    
    horizontalPodAutoscalerConfig:          
      behavior:                             
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 25
            periodSeconds: 60
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.prometheus
      metricName: nginx_ingress_controller_requests
      threshold: '1'
      query: sum(count_over_time(nginx_ingress_controller_requests{ingress="getting-started"}[1m]))
# With KEDA HTTP-ADD-ON
# kind: HTTPScaledObject
# apiVersion: http.keda.sh/v1alpha1
# metadata:
#     name: getting-started
#     namespace: examples
# spec:
#     host: getting-started.apps.BASE_DOMAIN
#     scaleTargetRef:
#         deployment: getting-started
#         service: getting-started
#         port: 80
#     replicas:
#         min: 0
#         max: 5